version: '3'
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    logging:
      driver: json-file
    networks:
      - lognet      
      
  server:
    container_name: robo-brain
    hostname: robo-brain
    depends_on:
      - postgres
    links:
      - 'postgres:postgres'
    restart: on-failure
    build:
      context: .
      dockerfile: robo-brain/Dockerfile
      
    volumes:
      - /robo-brain
    ports:
      - '3000:3000'
    tty: true  
    env_file:
      - robo-brain/envs/dev.env
    logging:
      driver: json-file
    networks:
      - lognet
    
      
  client:
    container_name: robo-do
    hostname: robo-do
    depends_on:
      - server
    links:
      - 'server:robo-brain'
    tty: true 
    restart: on-failure
    build:
      context: .
      dockerfile: robo-do/Dockerfile
    volumes:
      - /robo-do
    env_file:
      - robo-do/envs/dev.env
    logging:
      driver: json-file
    networks:
      - lognet

networks:
  lognet:
    driver: bridge